<a href="https://colab.research.google.com/github/aminsadruddin/NumPy-Exercises/blob/main/NumPy_ex_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy
NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,5,b,3])

NameError: name 'b' is not defined

In [ ]:
![](https://i.imgur.com/mg8O3kd.png) # below code on section

/bin/bash: -c: line 1: syntax error near unexpected token `https://i.imgur.com/mg8O3kd.png'
/bin/bash: -c: line 1: `[](https://i.imgur.com/mg8O3kd.png) # below code on section'


![](https://i.imgur.com/mg8O3kd.png)

In [ ]:
%%time
a = np.array([1,5,8,3])
b = 3
c = a*b
print(c)
print(a)
print(type(a))


[ 3 15 24  9]
[1 5 8 3]
<class 'numpy.ndarray'>
CPU times: user 860 µs, sys: 0 ns, total: 860 µs
Wall time: 2.93 ms


In [ ]:
# check version

print(np.__version__)

1.26.4


## Creating Arrays

In [ ]:
# NumPy Creating Arrays
# Use a tuple to create a NumPy array:
arr = np.array((1, 2, 3, 4, 5))

print(arr)
print(type(arr))
print(arr.shape)
print(arr.ndim)


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1


In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(type(arr1))
print(arr1.shape)
print(arr1.ndim)


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1


### 0-D Arrays

In [ ]:
# Dimensions in Arrays
# 0-D Arrays
# 0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.
# Create a 0-D array with value 42
a1 = np.array(42)
print(a1)
print(type(a1))
print(a1.shape)
print(a1.ndim)

42
<class 'numpy.ndarray'>
()
0


### 1-D Arrays

In [ ]:
# 1-D Arrays
#An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.
#These are the most common and basic arrays.

# eg, Create a 1-D array containing the values 1,2,3,4,5:

a2 = np.array([1,2,3,4,5])
print(a2)
print(type(a2))
print(a2.shape)
print(a2.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1


### 2-D Arrays

In [ ]:
# 2-D Arrays
# An array that has 1-D arrays as its elements is called a 2-D array.
# These are often used to represent matrix or 2nd order tensors.
#eg Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:

a3 = np.array([[1,2,3],[4,5,6]])

print(a3)
print(type(a3))
print(a3.shape)
print(a3.ndim)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)
2


### 3-D arrays

In [ ]:
#3-D arrays
#An array that has 2-D arrays (matrices) as its elements is called 3-D array.
#These are often used to represent a 3rd order tensor.
#Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:

a4 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a4)
print(type(a4))
print(a4.shape)
print(a4.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
<class 'numpy.ndarray'>
(2, 2, 3)
3


In [ ]:
# Check Number of Dimensions?  varuble.ndim
print(a1)
print(a2)
print(a3)
print(a4)

print("Number of Dimensions ")
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)
print(a4.ndim)



42
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
Number of Dimensions 
0
1
2
3


##Array Indexing

- Array indexing is the same as accessing an array element.
- You can access an array element by referring to its index number.
- The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [ ]:
w1, w2, w3 = 0.3, 0.2, 0.5

In [ ]:
karachi = [73, 67, 43]
lahore = [91, 88, 64]
quetta = [87, 134, 58]
sibi = [102, 43, 37]
hyderabad = [69, 96, 70]

In [ ]:
kanto_temp = 73
kanto_rainfall = 67
kanto_humidity = 43

kanto_yield_apples = kanto_temp * w1 + kanto_rainfall * w2 + kanto_humidity * w3
kanto_yield_apples

56.8

In [ ]:
print("The expected yield of apples in Kanto region is {} tons per hectare.".format(kanto_yield_apples))

The expected yield of apples in Kanto region is 56.8 tons per hectare.


In [ ]:
import numpy as np
karachi = np.array([73, 67, 43])
print (karachi)
print("Type:",type(karachi))
print("Shape:",karachi.shape)
print("Size:",karachi.size)
print("Dimention:",karachi.ndim)
print("Index:",karachi[0])



[73 67 43]
Type: <class 'numpy.ndarray'>
Shape: (3,)
Size: 3
Dimention: 1
Index: 73


In [ ]:
weights = np.array([w1, w2, w3])
print(weights)
print("Type:",type(weights))
print("Shape:",weights.shape)
print("Size:",weights.size)
print("Dimention:",weights.ndim)
print("Index:",weights[0])

[0.3 0.2 0.5]
Type: <class 'numpy.ndarray'>
Shape: (3,)
Size: 3
Dimention: 1
Index: 0.3


In [ ]:
# indexing
print(karachi)
print(karachi[0])
print(karachi[1])
print(karachi[0:1])
print(karachi[:-1])

a = np.array([0,1])
print(a)
# fancy array
print(karachi[a])

[73 67 43]
73
67
[73]
[73 67]
[0 1]
[73 67]


## Add , Sub , Multiply , divide


In [ ]:
#Multiply
print("multiply:",karachi * weights)
print("multiply:",np.multiply(karachi,weights))
#np.dot
print("dot:",karachi.dot(weights))
print("dot:",weights.dot(karachi))
print("dot:",np.dot(karachi,weights))
#addition
print("addition:",karachi + weights)
print("addition:",np.add(karachi,weights))
#subtraction
print("subtraction:",karachi - weights)
print("subtraction:",np.subtract(karachi,weights))
#divide
print("divide:",karachi / weights)
print("divide:",np.divide(karachi,weights))


multiply: [21.9 13.4 21.5]
multiply: [21.9 13.4 21.5]
dot: 56.8
dot: 56.8
dot: 56.8
addition: [73.3 67.2 43.5]
addition: [73.3 67.2 43.5]
subtraction: [72.7 66.8 42.5]
subtraction: [72.7 66.8 42.5]
divide: [243.33333333 335.          86.        ]
divide: [243.33333333 335.          86.        ]


## mean median std

In [ ]:
#mean median mode std
print("mean:",karachi.mean())
print("median:",np.median(karachi))
#print("mode:",np.mode(karachi))
print("std:",karachi.std())

mean: 61.0
median: 67.0
std: 12.96148139681572


## Copy vs View
- The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

- The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

- The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [ ]:
# copy
print(karachi)
k1 = np.copy(karachi)
print(k1)
k1[0] = 100
print(k1)
print(karachi)

[73 67 43]
[73 67 43]
[100  67  43]
[73 67 43]


In [ ]:
print(karachi)
k2 = karachi.view
print(k2) #no any object only view
print(karachi)

[73 67 43]
<built-in method view of numpy.ndarray object at 0x7f3bf697fd50>
[73 67 43]


## Arange and Linspace

In [ ]:
#arange
arr1 = np.arange(20)
print(arr1)
print(type(arr1))
print(arr1.shape)
print(arr1.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
<class 'numpy.ndarray'>
(20,)
1


In [ ]:
# linspace
arr2 = np.linspace(0,10,5)
print(arr2)
print(type(arr2))
print(arr2.shape)
print(arr2.ndim)

[ 0.   2.5  5.   7.5 10. ]
<class 'numpy.ndarray'>
(5,)
1


## arange , shape , reshape

In [ ]:
#shape
import numpy as np
# arange
a10 = np.arange(10)
print("arange",a10)
print("shape",a10.shape)
print("reshape",a10.reshape(2,5))
print("______________________")
a11 = np.arange(9).reshape(3,3)
print("arange",a11)
print("shape",a11.shape)
print("reshape",a11.reshape(3,3))
print("______________________")
a12 = np.arange(0,16,1)
print("arange",a12)
print("shape",a12.shape)
print("reshape",a12.reshape(4,4))
print("______________________")


arange [0 1 2 3 4 5 6 7 8 9]
shape (10,)
reshape [[0 1 2 3 4]
 [5 6 7 8 9]]
______________________
arange [[0 1 2]
 [3 4 5]
 [6 7 8]]
shape (3, 3)
reshape [[0 1 2]
 [3 4 5]
 [6 7 8]]
______________________
arange [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
shape (16,)
reshape [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
______________________


In [ ]:
#shape
arr = np.array([1, 2, 3, 4], ndmin=5)
print("arr",arr)
print('shape of array :', arr.shape)

arr1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print("arr1",arr1)
print("shape of array1 :",arr1.shape)


arr [[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)
arr1 [[1 2 3 4]
 [5 6 7 8]]
shape of array1 : (2, 4)


In [ ]:
a1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
a2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
# a4 = np.array(0,10,(3,3))
a5 = np.random.randint(0,10,(3,3)) #from randon function
a5a = np.random.rand(3,3) #from randon function
print(a1)
print("_________________")
print(a2)
print("_________________")
print(a3)
print("_________________")
print(a5)
print("_________________")
print(  a5a)
print("_________________")

[ 1  2  3  4  5  6  7  8  9 10 11 12]
_________________
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
_________________
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
_________________
[[3 3 6]
 [8 4 7]
 [9 7 4]]
_________________
[[0.82745382 0.57183663 0.58019909]
 [0.52197178 0.45934405 0.29863821]
 [0.33480817 0.78442765 0.59477312]]
_________________


In [ ]:
#reshape
a1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
a6 = a1.reshape(4,3)
print(a6)
print("_________________")
a7 = a1.reshape(2,3,2)
print(a7)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
_________________
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# Benefits of using Numpy arrays

In [ ]:
# Python lists
arr1 = list(range(1000000))
arr2 = list(range(1000000, 2000000))

# Numpy arrays
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [ ]:
%%time
result = 0
for x1, x2 in zip(arr1, arr2):
    result += x1*x2
result

CPU times: user 399 ms, sys: 0 ns, total: 399 ms
Wall time: 417 ms


833332333333500000

In [ ]:
%%time
np.dot(arr1_np, arr2_np)

CPU times: user 3.12 ms, sys: 18 µs, total: 3.13 ms
Wall time: 1.86 ms


833332333333500000

# Special arrays
- zeros array
- once array
- identity
- full

In [ ]:
#zaros
a1 = np.zeros(10)
#Once
a2 = np.ones(10)
#Identity
a3 = np.eye(3)
#full
a4 = np.full((3,5),3.14)
print("zeros array:", a1)
print("ones array:", a2)
print("identity array:", a3)
print("full array:", a4)



zeros array: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
ones array: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
identity array: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
full array: [[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]


In [ ]:
#zaros
a1 = np.zeros((3,3))
#Once
a2 = np.ones((3,3))
#Identity
a3 = np.eye(3)
#full
a4 = np.full((4,4),7)
print("zeros array:", a1)
print("ones array:", a2)
print("identity array:", a3)
print("full array:", a4)

zeros array: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
ones array: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
identity array: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
full array: [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [ ]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)
print(a4.dtype)

float64
float64
float64
int64


In [ ]:
print(a1.sum())
print(a2.sum())
print(a3.sum())
print(a4.sum())

0.0
9.0
3.0
112


## Broadicasting

- Scaler


In [ ]:
a4 = np.arange(9).reshape(3,3)
print(a4)
print(a4+3)
print(a4*2)
a5 = np.arange(3)
print(a5)
print(a4+a5)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]


# image from web

![](https://i.imgur.com/mg8O3kd.png)

<img src="https://i.imgur.com/LJ2WKSI.png" width="240">



In [ ]:
<img src="https://i.imgur.com/LJ2WKSI.png" width="240">
<img src="https://i.imgur.com/LJ2WKSI.png" width="380">

SyntaxError: invalid syntax (<ipython-input-40-cbcd477a44c6>, line 1)

<img src="https://i.imgur.com/LJ2WKSI.png" width="380">

In [ ]:
![](https://images.pexels.com/photos/674010/pexels-photo-674010.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1)

/bin/bash: -c: line 1: syntax error near unexpected token `https://images.pexels.com/photos/674010/pexels-photo-674010.jpeg?auto=compress'
/bin/bash: -c: line 1: `[](https://images.pexels.com/photos/674010/pexels-photo-674010.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1)'


![](https://images.pexels.com/photos/674010/pexels-photo-674010.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1)

<img src="https://images.pexels.com/photos/674010/pexels-photo-674010.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"width="240">

![](https://thumbs.dreamstime.com/b/white-flower-beautiful-hd-pic-japantown-215486907.jpg)

<img src="https://thumbs.dreamstime.com/b/white-flower-beautiful-hd-pic-japantown-215486907.jpg" width="240">

<img src="https://thumbs.dreamstime.com/b/white-flower-beautiful-hd-pic-japantown-215486907.jpg">

# Working with CSV data files

CSV is comma seprated txt file

Numpy also provides helper functions reading from & writing to files. Let's download a file `climate.txt`, which contains 10,000 climate measurements (temperature, rainfall & humidity) in the following format:

In [ ]:
# file load from git hub
# step 1
import urllib.request
import urllib.request

#step 2
# Change the URL to retrieve the raw CSV data instead of the HTML page.

urllib.request.urlretrieve('https://raw.githubusercontent.com/aminsadruddin/NumPy-Exercises/main/climate.csv','climate.txt')
#urllib.request.urlretrieve('https://github.com/aminsadruddin/NumPy-Exercises/blob/main/climate.csv','climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x7f3bf69a19f0>)

In [ ]:
climate_data = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)
# Syntex
# np.loadtxt("filenale.txt",delimiters=",")

In [ ]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [ ]:
climate_data.shape

(10000, 3)

We can now perform a matrix multiplication using the `@` operator to predict the yield of apples for the entire dataset using a given set of weights.

In [ ]:
weights = np.array([0.3, 0.2, 0.5])


In [ ]:
yields_data = climate_data @ weights

In [ ]:
# yields_data = climate_data * weights

In [ ]:
yields_data

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [ ]:
yields_data.shape

(10000,)

In [ ]:
ye = yields_data.reshape(10000,1)
ye.shape

(10000, 1)

Let's add the `yields` to `climate_data` as a fourth column using the [`np.concatenate`](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html) function.

In [ ]:
climate_results = np.concatenate((climate_data, yields_data.reshape(10000,1)), axis=1)

In [ ]:
climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [ ]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [ ]:
yields_data.reshape(10000,1)

array([[72.2],
       [59.7],
       [65.2],
       ...,
       [71.1],
       [80.7],
       [73.4]])

There are a couple of subtleties here:

* Since we wish to add new columns, we pass the argument `axis=1` to `np.concatenate`. The `axis` argument specifies the dimension for concatenation.

*  The arrays should have the same number of dimensions, and the same length along each except the dimension used for concatenation. We use the [`np.reshape`](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html) function to change the shape of `yields` from `(10000,)` to `(10000,1)`.

Here's a visual explanation of `np.concatenate` along `axis=1` (can you guess what `axis=0` results in?):

<img src="https://www.w3resource.com/w3r_images/python-numpy-image-exercise-58.png" width="300">

The best way to understand what a Numpy function does is to experiment with it and read the documentation to learn about its arguments & return values. Use the cells below to experiment with `np.concatenate` and `np.reshape`.

In [ ]:
np.savetxt('climate_results.csv',
           climate_results,
           fmt='%.2f',
           delimiter=',',
           header='temperature,rainfall,humidity,yeild_apples',
           comments='')

# NumPy ufunc

In [3]:
# Create your own ufunc for addition:
import numpy as np

def myadd(x, y):
  return x+y

a = myadd(2,1)
print(a)
myadd = np.frompyfunc(myadd, 2, 1)

print(myadd([1, 2, 3, 4], [5, 6, 7, 8]))

3
[6 8 10 12]


In [4]:
# Check if a function is a ufunc:
import numpy as np

print(type(np.add))

<class 'numpy.ufunc'>
